INSERT INTO ingredient_alias
    (detected_name, search_keyword, display_name, food_id, source, is_verified, enabled, created_at, updated_at)
VALUES
    ('apple', '사과', '사과', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Orange', '오렌지', '오렌지', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('orange', '오렌지', '오렌지', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('banana', '바나나', '바나나', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Banana', '바나나', '바나나', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Tomato', '토마토', '토마토', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tomato', '토마토', '토마토', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('carrot', '당근', '당근', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Broccoli', '브로콜리', '브로콜리', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('broccoli', '브로콜리', '브로콜리', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('chicken', '닭고기', '닭고기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Lemon', '레몬', '레몬', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('lemon', '레몬', '레몬', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Strawberry', '딸기', '딸기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('strawberry', '딸기', '딸기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Potato', '감자', '감자', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('potato', '감자', '감자', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('milk', '우유', '우유', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('bread', '빵', '빵', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mango', '망고', '망고', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('onion', '양파', '양파', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Onion', '양파', '양파', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cheese', '치즈', '치즈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corn', '옥수수', '옥수수', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('shrimp', '새우', '새우', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cauliflower', '콜리플라워', '콜리플라워', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mushroom', '버섯', '버섯', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('butter', '버터', '버터', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('peach', '복숭아', '복숭아', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('juice', '주스', '주스', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('chocolate', '초콜릿', '초콜릿', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('lettuce', '상추', '상추', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('meat', '고기', '고기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('beef', '소고기', '소고기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sugar', '설탕', '설탕', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ginger', '생강', '생강', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sausage', '소시지', '소시지', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('lime', '라임', '라임', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('apples', '사과', '사과', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('asparagus', '아스파라거스', '아스파라거스', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('aubergine', '가지', '가지', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('bacon', '베이컨', '베이컨', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('bananas', '바나나', '바나나', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('bazlama', '바즐라마', '바즐라마', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Beetroot', '비트', '비트', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('blueberries', '블루베리', '블루베리', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('carrots', '당근', '당근', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('chicken_breast', '닭가슴살', '닭가슴살', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('chocolate chips', '초콜릿 칩', '초콜릿 칩', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('courgettes', '주키니', '주키니', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cream', '크림', '크림', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('cream cheese', '크림치즈', '크림치즈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('creme fraiche', '크렘 프레슈', '크렘 프레슈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dates', '대추야자', '대추야자', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('eggs', '달걀', '달걀', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('flour', '밀가루', '밀가루', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('goat_cheese', '염소치즈', '염소치즈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('green beans', '그린빈', '그린빈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('green bell pepper', '청피망', '청피망', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('green chilies', '청고추', '청고추', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('green_beans', '그린빈', '그린빈', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ground_beef', '다진 소고기', '다진 소고기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ham', '햄', '햄', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('heavy_cream', '생크림', '생크림', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('labneh', '라브네', '라브네', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('lemons', '레몬', '레몬', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mineral water', '생수', '생수', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('mushrooms', '버섯', '버섯', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('olive', '올리브', '올리브', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('olives', '올리브', '올리브', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('parsley', '파슬리', '파슬리', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Peas', '완두콩', '완두콩', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('peppers', '고추', '고추', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('potatoes', '감자', '감자', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('red bell pepper', '홍피망', '홍피망', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('red grapes', '적포도', '적포도', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('red onion', '적양파', '적양파', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('salami', '살라미', '살라미', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sauce', '소스', '소스', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Shallot', '샬롯', '샬롯', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('spinach', '시금치', '시금치', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('spring onion', '쪽파', '쪽파', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('strawberries', '딸기', '딸기', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sweet_potato', '고구마', '고구마', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sweetcorn', '옥수수', '옥수수', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tomato paste', '토마토 페이스트', '토마토 페이스트', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('tomatoes', '토마토', '토마토', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('yellow bell pepper', '노란 파프리카', '노란 파프리카', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('yoghurt', '요거트', '요거트', NULL, 'ROBOFLOW_YOLO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (detected_name) DO UPDATE SET
    search_keyword = EXCLUDED.search_keyword,
    display_name = EXCLUDED.display_name,
    source = EXCLUDED.source,
    is_verified = EXCLUDED.is_verified,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;
